theme: minima
title: Using Jekyll To Deploy GitHub Pages
author: Jeroldine Akuye Oakley
description: This page was made using a guided course that introduced Jekyll and taught the course participants to use Jekyll to deploy a GitHub page.
